/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        bg: {
          base: "var(--bg-base)",
          surface: "var(--bg-surface)",
          elevated: "var(--bg-elevated)",
          overlay: "rgba(0,0,0,0.6)",
        },
        primary: {
          DEFAULT: "#059669",
          hover: "#047857",
          muted: "#065F46",
          light: "#D1FAE5",
          ghost: "rgba(5,150,105,0.12)",
        },
        accent: {
          DEFAULT: "#F97316",
          hover: "#EA580C",
          light: "#FFF7ED",
          ghost: "rgba(249,115,22,0.12)",
        },
        success: {
          DEFAULT: "#10B981",
          ghost: "rgba(16,185,129,0.12)",
        },
        warning: {
          DEFAULT: "#F59E0B",
          ghost: "rgba(245,158,11,0.12)",
        },
        error: {
          DEFAULT: "#EF4444",
          ghost: "rgba(239,68,68,0.12)",
        },
        info: {
          DEFAULT: "#3B82F6",
          ghost: "rgba(59,130,246,0.12)",
        },
        text: {
          primary: "var(--text-primary)",
          secondary: "var(--text-secondary)",
          tertiary: "var(--text-tertiary)",
          disabled: "var(--text-disabled)",
          inverse: "var(--text-inverse)",
          "on-primary": "#FFFFFF",
          "on-accent": "#FFFFFF",
        },
        border: {
          DEFAULT: "var(--border-default)",
          subtle: "var(--border-subtle)",
          active: "#059669",
        },
      },
      fontFamily: {
        sans: ["DMSans_400Regular", "system-ui", "sans-serif"],
        "sans-medium": ["DMSans_500Medium", "system-ui", "sans-serif"],
        "sans-semibold": ["DMSans_600SemiBold", "system-ui", "sans-serif"],
        "sans-bold": ["DMSans_700Bold", "system-ui", "sans-serif"],
      },
      fontSize: {
        display: ["36px", { lineHeight: "44px" }],
        h1: ["28px", { lineHeight: "36px" }],
        h2: ["22px", { lineHeight: "28px" }],
        h3: ["18px", { lineHeight: "24px" }],
        "body-lg": ["16px", { lineHeight: "24px" }],
        body: ["14px", { lineHeight: "21px" }],
        "body-sm": ["13px", { lineHeight: "18px" }],
        caption: ["11px", { lineHeight: "15px" }],
        overline: ["10px", { lineHeight: "16px", letterSpacing: "1px" }],
      },
      spacing: {
        0: "0px",
        0.5: "2px",
        1: "4px",
        1.5: "6px",
        2: "8px",
        2.5: "10px",
        3: "12px",
        3.5: "14px",
        4: "16px",
        5: "20px",
        6: "24px",
        7: "28px",
        8: "32px",
        9: "36px",
        10: "40px",
        12: "48px",
        14: "56px",
        16: "64px",
      },
      borderRadius: {
        sm: "6px",
        md: "10px",
        lg: "14px",
        xl: "18px",
        "2xl": "24px",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
